baseurl = "https://www.farmaceuticayounger.science/"
languageCode = "it"
title = "Farmacetica Younger"
defaultContentLanguage = "it"
enableRobotsTXT = true
canonifyURLs = true
paginate = 27

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
# removePathAccents = true

[author]
    name = "Farmaceutica Younger"

[permalinks]
  blog = "/:section/:year/:month/:slug/"
  pharmacronimi = "/:section/:slug/"
  hotthisweek = "/:section/:slug/"
  pharmaquotes = "/:section/:slug/"