baseurl = "https://www.farmaceuticayounger.science/"
languageCode = "it"
title = "Farmacetica Younger"
defaultContentLanguage = "it"
enableRobotsTXT = true
canonifyURLs = true
paginate = 12

copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."

[author]
    name = "Farmaceutica Younger"

[permalinks]
  pharmacronimi = "/:section/:title/"
  hotthisweek = "/:section/:title/"
  pharmaquotes = "/:section/:title/"